apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cad-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: cad-frontend.local
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cad-frontend
                port:
                  number: 80
