apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cad-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - frontend.tripico.fun
    secretName: frontend-tripico-fun-tls
  rules:
    - host: frontend.tripico.fun
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cad-frontend
                port:
                  number: 80
